# Generated by Django 3.2.3 on 2021-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
    ]
